"""empty message

Revision ID: db94ec523794
Revises: 90117aaa0ecf
Create Date: 2023-03-15 21:35:42.982390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'db94ec523794'
down_revision = '90117aaa0ecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('director', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'director')
    # ### end Alembic commands ###
