"""empty message

Revision ID: 31dc61fef167
Revises: 87970bb8813b
Create Date: 2023-03-15 21:36:59.159493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '31dc61fef167'
down_revision = '87970bb8813b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermovie', sa.Column('director', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermovie', 'director')
    # ### end Alembic commands ###
