"""empty message

Revision ID: 87970bb8813b
Revises: 14d61ddf184c
Create Date: 2023-03-04 01:12:40.430256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "87970bb8813b"
down_revision = "14d61ddf184c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
